//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int Id { get; set; }
        public Nullable<int> CourierId { get; set; }
        public int TransactionId { get; set; }
    
        public virtual Courier Courier { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
