//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.Details = new HashSet<Detail>();
        }
    
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string DeliveryLocation { get; set; }
        public long CustomerContactNumber { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public int ProductId { get; set; }
        public int ProductQty { get; set; }
        public double DeliveryCharge { get; set; }
        public double AdvancePaid { get; set; }
        public double TotalPrice { get; set; }
        public int DeliveryStatus { get; set; }
        public Nullable<long> TransactionNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail> Details { get; set; }
        public virtual Product Product { get; set; }
    }
}
