//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBakingShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.Details = new HashSet<Detail>();
        }
    
        public int Id { get; set; }

        [Display(Name = "Customer Id")]
        public int CustomerId { get; set; }

        [Display(Name = "Delivery Location")]
        public string DeliveryLocation { get; set; }

        [Display(Name = "Customer Contact Number")]
        public long CustomerContactNumber { get; set; }

        [Display(Name = "Delivery Date")]
        public System.DateTime DeliveryDate { get; set; }

        [Display(Name = "Product Id")]
        public int ProductId { get; set; }

        [Display(Name = "Product Qty")]
        public bool ProductQty { get; set; }

        [Display(Name = "Delivery Charge")]
        public double DeliveryCharge { get; set; }

        [Display(Name = "Advance Paid")]
        public double AdvancePaid { get; set; }

        [Display(Name = "Total Price")]
        public double TotalPrice { get; set; }

        [Display(Name = "Delivery Status")]
        public bool DeliveryStatus { get; set; }

        [Display(Name = "Transaction Number")]
        public Nullable<long> TransactionNumber { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail> Details { get; set; }
        public virtual Product Product { get; set; }
    }
}
